services:
  env: 
    extends: 
      file: compose.base.yml
      service: generic
    profiles:
      - env
    container_name: env-tests
    hostname: env-tests
    env_file:                   # Defines container environment variables - NOT compose interpolated variables
      - env/container.env
      # Could also define the container's environment file using the interpolated environment variables:
      - ${ENV_OVERRIDE:-env/container.env}       # Will use the $CONTAINER_ENV defined within .env as the filename for the container environment
    ports: 
      - ${PORT:?Port must be specified!}      # To interpolate from a different .env file, use `docker compose -e another.env`
    environment:
      - another_var=${INTERPOLATED_VAR:-default value}
      # Overrides variables defined through `env_file`