services:
  amd: 
    image: deanayalon/test-multiplatform:amd
    build:
      platforms:
        - linux/amd64
  arm:
    image: deanayalon/test-multiplatform:arm
    build:
      platforms:
        - linux/arm64/v8
  both:
    image: deanayalon/test-multiplatform:both
    build:
      platforms:
        - linux/amd64
        - linux/arm64/v8
