FROM alpine
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /platform

# Synthasize filenames turning `/` into `-`
RUN echo "Target platform - $TARGETPLATFORM" > platform & \
    echo "Built on $BUILDPLATFORM" > "built-on" & \
    echo "Architecture - $(uname -m)" > arch

CMD cat $(ls)