name: tests
services:
  scratch: 
    image: deanayalon/scratch
    container_name: scratch
    build: 
      dockerfile_inline: FROM scratch
    command: [""]

  tail:
    image: deanayalon/scratch:tail
    container_name: tail
    build:
      dockerfile: dockerfile.tail

  shell:
    image: deanayalon/scratch:shell
    build:
      dockerfile: dockerfile.shell

  cp:
    image: deanayalon/scratch:cp
    build:
      dockerfile_inline: |
        FROM scratch
        COPY --from=alpine /lib/apk/db/installed .
    command: 'tail -f /dev/null'
    # Test docker cp on scratch images